includes("xmake.common.lua")
opt_defaults()
set_languages("clatest", "cxxlatest")
set_toolchains("gcc")

add_requires("gtest", {system = false})
add_requires("benchmark", {system = false})

-- GCC (libstdc++)
target("test_unit_gcc")
    set_kind("binary")
    add_files("tests/test_unit.cpp")
    add_packages("gtest")

target("bench_gcc")
    set_kind("binary")
    add_files("benchmarks/bench.cpp")
    add_packages("benchmark")
    set_optimize("fastest")
    add_cxxflags("-fno-rtti", "-march=native", "-mtune=native", "-flto")
    add_ldflags("-flto")

target("bench_debug_opt_gcc")
    set_kind("binary")
    add_files("benchmarks/bench.cpp")
    add_packages("benchmark")
    set_optimize("fastest")
    set_symbols("debug")
    add_cxxflags("-march=x86-64-v3", "-mtune=generic")
