add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})

set_toolchains("msvc")
set_languages("c++latest")

add_requires("gtest", {system = false})
add_requires("benchmark", {system = false})

-- MSVC test (Windows)
target("test_unit_msvc")
    set_kind("binary")
    add_files("src/test_unit.cpp")
    add_packages("gtest")
    add_includedirs("src/include")
    set_toolchains("msvc")
    add_cxxflags("/utf-8")

-- MSVC benchmark (Windows)
target("bench_msvc")
    set_kind("binary")
    add_files("src/bench.cpp")
    add_includedirs("src/include")
    add_packages("benchmark")
    set_optimize("fastest")
    set_toolchains("msvc")
    add_cxxflags("/utf-8")